# Generated by Django 3.2 on 2021-04-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField()),
                ('status', models.CharField(choices=[('unscraped', 'Unscraped'), ('scraped', 'Scraped')], default='unscraped', max_length=120)),
            ],
        ),
    ]
